swagger:
  base:
    apiPath:  #swagger根目录
server:
  error:
    whitelabel:
      enabled: false
  port: 9030  # 服务端口
  tomcat:
    uri-encoding: UTF-8   # tomcat的URI编码
    max-threads: 800      # tomcat最大线程数，默认为200

logging:
  config: classpath:logback.xml  # 制定日志文件配置

base:
  isonline: 0 #正式测试环境的标记 0:非正式 1:正式
  filepath: /data/springboot/     #上传文件的缓存位置
  apilinkurl: http://172.16.20.82/api/
  jianguan: http://ycapi.syhdoctor.com/jianguan_test/
  beian: http://ycapi.syhdoctor.com/beian_test/
  picdomain: https://resource.syhdoctor.com/
  doctorpicurl: http://172.16.20.82:9030/localdoctor/upload/getLocalFile/ #医生相关图片前缀
  apkpicurl: https://172.16.20.82:9030/localdoctor/upload/downfile/  #医生相关图片前缀
  localimg: http://172.16.20.82:9030/Local/Upload/getLocalImg/
  weblinkurl: http://172.16.20.82/
  websocketlinkurl: http://127.0.0.1:9100/


#微信公众号的配置
wechat:
  syh:  #育儿24小时公众号
    appid: wxf95d9d70sdf5f9519
    secret: 51f569eaaf62b9dsf7f8253c9038d8689
    mchId: 1232964302
    mchKey: xNnEbhq2iLsdfsQPQhULTsvYPYNeBJ66
    keyPath: apiclient_cert.p12的绝对路径、 包含了私钥信息的证书文件

#数据库连接配置
spring:
  servlet:
    multipart:
      max-file-size: 100Mb     #上传文件大小限制
      max-request-size: 100Mb  #上传文件大小限制
  mvc:
    favicon:
      enabled: false  # tomcat ico 图标定制
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.20.84:3306/syhdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: windows_2013
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      uri: mongodb://test:windows_2013@172.16.20.84:27017/testdb  #mongodb数据库
  redis:
    host: 172.16.20.84 # Redis服务器地址
    port: 6379          # Redis服务器连接端口
    password: windows_2013   # Redis服务器连接密码（默认为空）
    database: 0         # Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8   # 连接池中的最大空闲连接
        min-idle: 0   # 连接池中的最小空闲连接
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 10000    # 连接超时时间（毫秒）



